### PR TITLE
Add phpcs checks to PRs for backdrop/backdrop.

### PR DESCRIPTION
**Pull request by serundeputy**

### CODE REVIEW

**Comment by Gormartsen** [comment]
Looks correct, but need to be tested
Also After this PR merges, backdrop/backdrop#2244 need to be merged in master as well, or all tests will complain for missing test file core/misc/zen-ci/run_phpcs.sh

**Comment by serundeputy** [comment]
@quicksketch any harm in merging this so we can see if it fires the phpcs-diff-only check?

**Comment by quicksketch** [comment]
Sure, let's give it a go... I'll merge and then deploy onto backdropcms.org.

**Comment by quicksketch** [comment]
We've been seeing very long run times on tests, @Gormartsen thinks this is probably related. As the PHPCS check didn't work quite right even when it did run, I've reverted this PR and redeployed to see if that resolves the problem with extremely long run times.

**Pull request merged**
