### PR TITLE
Issue #560: Provide json endpoint /api/backdrop-news.

### PR DESCRIPTION
**Pull request by serundeputy**

### CODE REVIEW

**Comment by jenlampton** [comment]
@serundeputy is this a branch on the current repo? Or on your clone? I can't grab it wherever it is now...

**Comment by jenlampton** [comment]
This is really good!  A few thoughts:

1) the content type should probably not include "news" since we already have a news node type and that could get confusing. How about "Announcements"? I have another site where these things are called "Alerts" but though that's nice and short, it seems maybe too alarming for these kinds of promotions. Naming things is hard...

2) The link field should be a link and not a text field so that we can get better validation. (Is there a reason you chose a text-short field here?)

1) the path for the json feed should end in .json, so `api/news.json` instead of `api/news` Maybe we should pull news out of here too, so `api/announcements.json`, or whatever we decide to use above?  

1) I'm not in love with the `/api/' in the URL. I can see how having something there would make sense if/when we add other types of content, but since we do have a "Backdrop API" which is different than the "backdropcms.org API" I'm worried that it could get confusing. I'd be tempted to name it something like "feed" or "data" instead. Or leave it out entirely?

Otherwise, I love this :) If we can decide what to name things, this will be good to go!

**Comment by stpaultim** [comment]
> the content type should probably not include "news" since we already have a news node type and that could get confusing. How about "Announcements"? I have another site where these things are called "Alerts" but though that's nice and short, it seems maybe too alarming for these kinds of promotions. Naming things is hard...

I agree. "Announcements" was my first thought. I also like "Notification."

Other options:
* Alerts 
* Bulletins
* Broadcast
* Release
* Notification / Notice

**Comment by docwilmot** [comment]
Will those be used anywhere else? Could we call then dashboard announcements so its obvious what theyre for? Unless we have another purpose for them and that then would be too specific.

**Comment by jenlampton** [comment]
> Will those be used anywhere else?

I don't think we know yet :) 

Why don't we call them "Dashboard announcements" as a human-readable name and just "announcements" as the machine name. Then if we decide to re-purpose them later we can change the human name without it affecting anything else?

**Comment by docwilmot** [comment]
At the risk of bike-shedding, I hadnt read @stpaultim comment above, and I now prefer dashboard notifications  :smile:

**Comment by stpaultim** [comment]
I tried to provide a PR against this PR. Not sure if it worked. 
https://github.com/backdrop-ops/backdropcms.org/pull/565

**Comment by serundeputy** [comment]
@stpaultim i've merged your changes from #565  into this pr.

**Comment by serundeputy** [comment]
> the content type should probably not include "news" since we already have a news node type and that could get confusing. How about "Announcements"? I have another site where these things are called "Alerts" but though that's nice and short, it seems maybe too alarming for these kinds of promotions. Naming things is hard...

  - [x] @stpaultim renamed the content type to `notification` with human readable name Dashboard Notification.

> The link field should be a link and not a text field so that we can get better validation. (Is there a reason you chose a text-short field here?)

  - [ ]  I'll have to look into this one so @TODO
    * pretty sure the validation checks for proper protocol and valid link structure, but not for an actual valid status 200 link, but meh.

> the path for the json feed should end in .json, so api/news.json instead of api/news Maybe we should pull news out of here too, so api/announcements.json, or whatever we decide to use above?

  - [ ] I disagree with this; we are not pointing to and serving a raw file here; we are providing an API endpoint to generate and serve json.  None of the other APIs i've built or interacted with (this includes github, google, mailchimp, and may others) use an extension for their endpoints.
  * so we need to decide if we are going to do this or not; I vote no and we stick to trusted patterns

> I'm not in love with the `/api/' in the URL. I can see how having something there would make sense if/when we add other types of content, but since we do have a "Backdrop API" which is different than the "backdropcms.org API" I'm worried that it could get confusing. I'd be tempted to name it something like "feed" or "data" instead. Or leave it out entirely?

  - [ ] all the APIs i've built and interacted with namespace the endpoints with something, most of the with `/api/ (i can not think of one that is not `/api`),  so i think the namespacing is a good idea and we should stick to a known pattern.
  * I vote for teh `/api` namespace as it is developer friendly

**Comment by stpaultim** [comment]
I don't really have opinions on any of the outstanding questions here.

**Comment by stpaultim** [comment]
Just trying to do a little research that might help move this along. Here are some resources (i think this is what we are looking for):

7 Rules for REST API URI Design
https://blog.restcase.com/7-rules-for-rest-api-uri-design/

REST Resource Naming Guide
https://restfulapi.net/resource-naming/

A SPECIFICATION FOR BUILDING APIS IN JSON
https://jsonapi.org/recommendations/#urls

Seems pretty clear that we should NOT use .json in the URL based upon what I saw. I found examples, including New York Times that do use .json in the api url, but I also found clear and specific guidance against it in the articles above.

In terms of using /api/ in the URL, I did not find any definitive advice on this. There seem to be lots of examples where there is an api subdomain like this:

`http://api.example.com/louvre/leonardo-da-vinci/mona-lisa`

There are lots of examples that include both /api/ and a version number in the url /v2/, but these examples felt a little dated. 

`https://blog.mwaysolutions.com/sample/api/v1/cars`

> but since we do have a "Backdrop API" which is different than the "backdropcms.org API" I'm worried that it could get confusing.

I see this concern and given our focus on end users / site owners / editors I can see the argument for using a path like, which is slightly less obscure. 

https://www.backdropcms.org/data/notifications 

But, I also hear @serundeputy argument that many developers are used to /api/ and it's not clear to me than anyone but developers would be interacting with (or ever seeing) this URL on Backdropcms.org 

Since @serundeputy is in favor (recommends) that we use /api/ and @jenlampton was at best on the fence, and I don't think the implications are that serious right now - I lean towards just using /api/. The decision we are making is much more about www.backdropcms.org than it is about the core product.  

How about this:

https://www.backdropcms.org/api/notifications

In the future, we could theoretically have:

https://www.backdropcms.org/api/events
https://www.backdropcms.org/api/modules
https://www.backdropcms.org/api/mentions

I don't feel strongly, but I'm going on the record to help move this along.

**Comment by stpaultim** [comment]
On today's dev call, @quicksketch suggested that we should make the data model for the output of the json feed less Backdrop specific if possible (my choice of words, not his). For example, he mentioned references to nodes. He suggested that the goal would be that it would not be obvious that the feed is coming from a Backdrop CMS site if one did not know that. 

I am not sure why this is important, given that it's a Backdrop CMS news feed from BackdropCMS.org to be read by a module in Backdrop core. Maybe there are security implications.

But, assuming this isn't too hard to change, why not?

If it is hard to change, we might want to discuss this some more.   

I can't verify this, because without actually seeing a sample of the output, I'm less clear on what the output will look like based upon looking at the code.

**Pull request closed without merging**
