### PR TITLE
Update backdrop drush to 1.0.0 in `.lando.yml`

### PR DESCRIPTION
**Pull request by klonos**

### CODE REVIEW

**Comment by jenlampton** [comment]
This won't work on Pantheon. Can we try to do something that will work
there too? (Or also?)

**Comment by serundeputy** [comment]
Pantheon ignores this file entirely;

**Comment by jenlampton** [comment]
Right. I thought I saw "on Pantheon" in the title, and was pointing out the
same ;)

**Comment by BWPanda** [comment]
This is/has already been committed: https://github.com/backdrop-ops/backdropcms.org/blob/master/.lando.yml#L7

**Pull request closed without merging**
