### PR TITLE
Issue #163: Clean up profile edit page

### PR DESCRIPTION
**Pull request by wesruv**
Reordered user form and shoved some fields in collapsible fieldsets
Added styles for prettiness
Also slipped in fix for Issue #144

### CODE REVIEW

**Comment by jenlampton** [comment]
Er, well I found some problems. I was thinking it might be good-enough as is since no one was using it yet, but my javascript ended up all broken. Regular users couldn't open fieldsets, and admin users ...  well I don't know what was wrong. But I don't think this is good enough as-is :)

**Comment by jenlampton** [comment]
@wesruv I would say it is less important that it looks good on mobile immediately. If we can get it looking good on desktop (with no js issues?) we can push that and then work on mobile later. Your screenshots are looking fantastic, but my local isn't quite the same. maybe you can help me with deployment steps (git pull / config import / clear caches?) to see if there is something I am missing.

**Comment by wesruv** [comment]
@jenlampton there's a JS issue on the user edit page:
Uncaught TypeError: Cannot read property 'confirmTitle' of undefined `user.js:19`

I think I hacked my way out of the issue on my local... not sure what the appropriate fix is.

**Comment by jenlampton** [comment]
Ah, that's likely what I was seeing then.  I'll see if I can sort that out :)

**Comment by jenlampton** [comment]
Trying this again today...

**Comment by jenlampton** [comment]
I've re-committed this work, with one change: I didn't like the idea of changing the icon for "drag to re-order" without some more evidence that the new hamburglar icon is better for that job, so I put that back the way it was before (but slightly adjusted the padding).

Let's revisit the hamburglar / arrows icon issue in the new theme and if we decide to that we can make the change here too - when that new theme goes in.

**Comment by wesruv** [comment]
Re: Hamburglar / Drag icon
cc: @mikemccaffrey 

I was trying to mimic this: 
image

My gut is the cross arrow is a mouse thing, and it's ugly (which isn't the best reason to hate on icon's for UX)

This might be a good improvement, it's a version of the latest iOS drag handle:
image


A quick google search shows others, I don't think Gmail's 6 dots is intuitive
https://www.google.com/search?q=drag+handle+icon&espv=2&biw=1333&bih=998&source=lnms&tbm=isch&sa=X&ved=0ahUKEwi1nbnwlrnLAhVFnIMKHfHJCDUQ_AUIBigB#

**Comment by wesruv** [comment]
Here's google's material design drag handle:
image

Modern iOS' drag handle:
image

**Comment by jenlampton** [comment]
It just doesn't read as "drag me up down right or left". It reads as "I'm a menu, click me". Can we make the current set of arrows less ugly instead, maybe?  In general, I don't think we should be using iOS as a guide for UX stuff anymore, as less than half the population will be accustomed to those icons. It would be good if we could find something that's more universal to model after.

**Comment by wesruv** [comment]
That thing doesn't get prettier, if you simplify it it becomes a celtic cross, change it and it loses it's identity. But if the consensus is that makes the most sense, I'll go with it.

I think it's better suited as a mouse cursor than a handle, and if we use a better handle icon, I think the cursor should be a grabby hand instead of that cursor.
image


Re: not using iOS as a guide:
iOS, Android, FontAwesome (it's called 'reorder' in FA), and likely others are all using this icon for a draggable handle; this is the icon that all the cool kids are using in new designs. I feel like the consensus is with this kind of icon.

The difference between menu and drag handle in those design systems is that drag handle is always low contrast, and menu is in a high contrast and in a top corner of the application. Dropdown menus in the application usually use a different icon (e.g. the ellipsis, gear, etc).

I see the potential confusion, both icons are trying to depict a list, but context and design should inform the user what it is.

An aside... 
The drag handle seems to always be on the right side in the design systems where I see it used, maybe that's where our drag handle should go? That's where we put action links in our tables, might make more sense that way?

**Comment by klonos** [comment]
I'm with @jenlampton here. I see what you mean @wesruv when you say that this icon depicts a list, but although iOS and Android is popular, the handle they have is for reordering things *vertically*. It doesn't account for moving things left/right (think menu items, term parents and book pages).

I see how changing the cursor to a hand grip makes sense. I don't agree with moving to the right side though. Although it seems to be a pattern with iOS and Android again, It simply wouldn't work and feel right with moving things horizontally. We usually have things that can be arranged in a hierarchical way to the left and some of them can be child items of others if dragged to the right (perhaps it would make sense to have them to the right in LTR languages, but not sure).

**Comment by wesruv** [comment]
Good catch, I wasn't thinking about the hierarchical stuff. 

That definitely rules out moving it to the right side.

**Pull request merged**
