### PR TITLE
Fixed some theme issues and added all markup and styles necessary for project search

### PR DESCRIPTION
**Pull request by wesruv**
Here's a video walking through the changes:
https://drive.google.com/file/d/0BzY54DXqV6bNdGxhcW1FZmFNX00/view?usp=sharing

Added layouts for modules, layouts, and themes, they're all the same... not sure if there's a good way to use one layout?
Added views config, which is slightly modified from what was given to me
Added interim styles for project pages, until we get the content spit out so it can be styled like the design
Added a utility class 'l-content-wrapper' which is used to contain content
* Normally this would be put on the outer wrapper of a block, but if a block has a bg color that should span the width of the page the class should go on an inner element
Reworked how the menu flies out of the side, added margin to the body instead of an outer div
* This was to make sure all content will be in the viewable area (selfishly my krumo output was hiding behind the drawer)
Changed the way the Backdrop logo is added at mobile to prevent content overlapping
Fixed misc. bugs that were happening at smaller screensizes by adding extra media query styles that maintained the same appearance at desktop

### CODE REVIEW

**Comment by wesruv** [comment]
I haven't fixed the mobile bug where the word 'Page' doesn't show up for Page one. But it's late and I'll do that later.

**Comment by quicksketch** [comment]
Woowoowoo! I'd love to get this up ASAP. :+1:

**Comment by docwilmot** [comment]
Agreed with the woowoo, it looks really nice.

One thing I looked for though was what the front page links to project pages would look like. Different issue though.

**Comment by quicksketch** [comment]
Woo, this is fun working with exported config! Thanks for doing that Wes. However, merging conflicting Views config is no piece of cake. I think I have it merged locally.

**Comment by quicksketch** [comment]
Some notes on implementation:

- You're right that there's no way to make a layout change on multiple different paths (e.g. /modules, /themes, and /layouts). So separate layouts is the only way to go on this.
- I fixed the .htaccess file in the merge so that these paths should work after you pull down master.

I found a couple of things but nothing that can't be fixed:

- There was an unclosed `<div>` in `layout--double-fixed.tpl.php`.
- The admin interface for editing the double-fixed layout hadn't been updated for the new markup.
- Messages and the "action links" didn't have the `l-content-wrapper` class so they weren't getting centered quite right.

Overall, fantastic! Thanks for all this theming as well as the cleanup! I'll get this pushed into master shortly. As these pages aren't really "live" yet there's no reason to delay.

**Comment by quicksketch** [comment]
This is now up in production. Nice job @wesruv!

**Comment by docwilmot** [comment]
Beautiful.

**Comment by wesruv** [comment]
@quicksketch did you fix all the things you noted in the implementation? Looks like it, but I wanted to double check.

**Comment by quicksketch** [comment]
> did you fix all the things you noted in the implementation? Looks like it, but I wanted to double check.

Yep!

**Pull request merged**
