### PR TITLE
CiviCRM 5.36.0 and settings files

### PR DESCRIPTION
**Pull request by scoobird**
WIP CiviCRM

### CODE REVIEW

**Comment by bugfolder** [comment]
Back-reference to issue https://github.com/backdrop-ops/backdropcms.org/issues/789.

**Comment by larsdesigns** [comment]
Can we update the pull request to include CiviCRM version 5.38 instead of 5.36?

**Comment by scoobird** [comment]
* Install cv utility
* create civicrm database & note credentials
* create civicrm.settings.local.php using template
* Delete civicrm.settings.php
* Install civicrm: [backdropcms.org]/modules/civicrm/install/index.php?civicrm_install_type=backdrop
* Add site key from civicrm.settings.php to civicrm.settings.local.php
* Checkout civicrm.settings.php to discard changes in the repo (make a backup copy of this file in case we miss a setting here)
* Configure basic site info per Civi warning messages
* Add a privileged civicrm cron user (civicron) -- this user may have the admin role, or have a role with limited admin permissions to CiviCRM including CiviMail and CiviReport.
* Add a cron job for civicrm every 5 minutes: 
@*/5 * * * * /usr/local/bin/cv api job.execute --user=civicron --cwd=/path/to/site@

**Comment by BWPanda** [comment]
I just made a change to the Tugboat config to fix an issue with PR previews. In order to get the Tugboat preview working, please rebase the PR.

**Comment by larsdesigns** [comment]
This seems to have been completed some time ago. Perhaps in a different issue. The site is up and running on version 5.47.4. 

No further tasks. Closing..

**Pull request closed without merging**
